#!/bin/bash
# Auto-generated by maestro pipeline — verification commands for this task
# Run this script to verify all requirements are met.
set -e

echo '=== Project Test Suite ==='
go vet ./...
go test ./...
go run ./cmd/ok-gobot memory eval
make test
go build ./cmd/ok-gobot/

echo '=== Requirement Verification ==='
echo 'Requirement 1: User sends a Telegram command/message to ok-gobot.'
go test ./...

echo 'Requirement 2: ok-gobot performs the workflow itself, without delegating to OpenClaw runtime.'
go test ./internal/agent/...

echo 'Requirement 3: User receives the expected result/artifact/link in Telegram.'
go test ./...

echo 'Requirement 4: The result writes to the same target storage used by the existing kobi/OpenClaw ...'
go test ./internal/storage/...

echo 'Requirement 5: The smoke is repeatable on the LXC deployment.'
go test ./...

echo 'Requirement 6: Do not treat markdown-only skill install/list/audit as workflow parity.'
go test ./internal/bootstrap/...

echo 'Requirement 7: Do not treat service active as user workflow success.'
go test ./internal/agent/...

echo 'Requirement 8: Do not prioritize new infra unless it directly unlocks one parity row.'
go test ./internal/browser/...

echo 'Requirement 9: Finish and live-smoke PR #389 for `/video_summary`.'
go test ./...

echo 'Requirement 10: Add the next native workflow row: `youtube-karaoke`.'
go test ./internal/browser/...

echo 'Requirement 11: Configure and smoke memory parity on the LXC instance.'
go test ./internal/agent/...

echo 'Requirement 12: Keep this issue open until the replacement claim is true for the actual kobi wor...'
go test ./internal/worker/...

echo 'All verifications passed.'
