#!/bin/bash
# Auto-generated by maestro pipeline — verification commands for this task
# Run this script to verify all requirements are met.
set -e

echo '=== Project Test Suite ==='
go vet ./...
go test ./...
go run ./cmd/ok-gobot memory eval
go build ./cmd/ok-gobot/
make test

echo '=== Requirement Verification ==='
echo 'Requirement 1: `roles list` / `/roles` show no **model tier**, even though epic AC requires it ...'
go test ./internal/cron/...

echo 'Requirement 2: `roles show <name>` (CLI, `internal/cli/roles.go`) prints only Name, Worker, App...'
go test ./internal/ai/...

echo 'Requirement 3: `/role <name>` (Telegram, `internal/bot/role_commands.go`) likewise omits all bu...'
go test ./...

echo 'Requirement 4: `roles list` (`internal/cli/roles.go`, `newRolesListCommand`) gains a `MODEL` co...'
go test ./...

echo 'Requirement 5: `roles show <name>` prints `Model` (when set) and any non-zero budget/policy fie...'
go test ./internal/tui/...

echo 'Requirement 6: `/role <name>` (`internal/bot/role_commands.go`, `handleRoleCommand`) shows the ...'
go test ./...

echo 'Requirement 7: `/roles` (`handleRolesCommand`) includes the model in each role line when `m.Mod...'
go test ./internal/bot/...

echo 'Requirement 8: A test asserts a role with `model:`, `max_tool_calls:`, `max_cost_usd:` set has ...'
go test ./internal/bot/...

echo 'Requirement 9: A test asserts `roles list` output contains the model value for a role that sets...'
go test ./internal/bot/...

echo 'Requirement 10: A bot-side test asserts `handleRoleCommand` output includes the model and a budg...'
go test ./internal/cli/...

echo 'Requirement 11: `go build ./...` and `go test ./internal/cli/... ./internal/bot/... ./internal/r...'
go test ./...

echo 'Requirement 12: `internal/cli/roles.go` — `newRolesListCommand` (add column), `newRolesShowCom...'
go test ./...

echo 'Requirement 13: `internal/cli/roles_test.go` — new/extended assertions'
go test ./...

echo 'Requirement 14: `internal/bot/role_commands.go` — `handleRoleCommand`, `handleRolesCommand`'
go test ./...

echo 'Requirement 15: `internal/bot/role_commands_test.go` — new/extended assertions'
go test ./...

echo 'Requirement 16: Read-only reference: `internal/role/manifest.go` (field definitions; do not modi...'
go test ./...

echo 'Requirement 17: Fixture reference: `internal/role/prebuilt/*.md` (existing budget values)'
go test ./...

echo 'Requirement 18: No new manifest fields (no filesystem-roots or network-allowlist field exists on...'
go test ./internal/agent/...

echo 'Requirement 19: No changes to budget/policy enforcement, `ToDelegationJob`, scheduling, or job e...'
go test ./internal/bot/...

echo 'Requirement 20: No "last run" / "enabled state" columns (those depend on cron/job joins — sepa...'
go test ./internal/agent/...

echo 'Requirement 21: No TUI/web/API changes (`#289` territory).'
go test ./...

echo 'Requirement 22: No changes to `roles run`, `roles enable/disable`, or any write path.'
go test ./internal/memory/...

echo 'All verifications passed.'
