#!/bin/bash
# Auto-generated by maestro pipeline — verification commands for this task
# Run this script to verify all requirements are met.
set -e

echo '=== Project Test Suite ==='
go test ./...
go run ./cmd/ok-gobot memory eval
make test

echo '=== Requirement Verification ==='
echo 'Requirement 1: Add internal/role/prebuilt/prototype-builder.md.'
go test ./...

echo 'Requirement 2: Suggested tools: file, patch, local, frontend_verify, message.'
go test ./internal/tools/...

echo 'Requirement 3: The role should create or modify a minimal runnable frontend in the assigned wor...'
go test ./internal/bot/...

echo 'Requirement 4: The role should run or prepare a local dev server.'
go test ./internal/rolejob/...

echo 'Requirement 5: The role should call frontend_verify for browser proof.'
go test ./internal/tools/...

echo 'Requirement 6: The role should produce a short final report with screenshot or artifact referen...'
go test ./internal/artifacts/...

echo 'Requirement 7: Dangerous shell behavior must still respect policy and approval settings.'
go test ./internal/agent/...

echo 'Requirement 8: Add tests proving the role loads as bundled and exposes expected metadata.'
go test ./internal/role/...

echo 'Requirement 9: ok-gobot roles list shows prototype-builder as bundled.'
go test ./internal/cli/...

echo 'Requirement 10: /roles shows prototype-builder with a useful short description or quick command.'
go test ./internal/bot/...

echo 'Requirement 11: ok-gobot roles show prototype-builder displays tools, worker tier, approval mode...'
go test ./internal/tools/...

echo 'Requirement 12: Manual acceptance target: /role_run prototype-builder Build a blue 3D rocket lau...'
go test ./internal/rolejob/...

echo 'Requirement 13: go test ./... passes.'
go test ./internal/agent/...

echo 'Requirement 14: Do not make this role scheduled by default.'
go test ./internal/bot/...

echo 'Requirement 15: Do not bypass approval or policy for dangerous local commands.'
go test ./internal/agent/...

echo 'All verifications passed.'
